Analysis of Divvy Bike Share data from the city of Chicago for the years 2018-2019 (datasets found at https://divvy-tripdata.s3.amazonaws.com/index.html)

In [97]:
import numpy as np 
import pandas as pd 

q1_2018 = pd.read_csv('/kaggle/input/datasets/elodiebarthout/bikeshare-chicago-2018-2019/Divvy_Trips_2018_Q1.csv')
q2_2018 = pd.read_csv('/kaggle/input/datasets/elodiebarthout/bikeshare-chicago-2018-2019/Divvy_Trips_2018_Q2.csv')
q3_2018 = pd.read_csv('/kaggle/input/datasets/elodiebarthout/bikeshare-chicago-2018-2019/Divvy_Trips_2018_Q3.csv')
q4_2018 = pd.read_csv('/kaggle/input/datasets/elodiebarthout/bikeshare-chicago-2018-2019/Divvy_Trips_2018_Q4.csv')

q1_2019 = pd.read_csv('/kaggle/input/datasets/elodiebarthout/bikeshare-chicago-2018-2019/Divvy_Trips_2019_Q1.csv')
q2_2019 = pd.read_csv('/kaggle/input/datasets/elodiebarthout/bikeshare-chicago-2018-2019/Divvy_Trips_2019_Q2.csv')
q3_2019 = pd.read_csv('/kaggle/input/datasets/elodiebarthout/bikeshare-chicago-2018-2019/Divvy_Trips_2019_Q3.csv')
q4_2019 = pd.read_csv('/kaggle/input/datasets/elodiebarthout/bikeshare-chicago-2018-2019/Divvy_Trips_2019_Q4.csv')

print('Setup complete.')

Setup complete.

In [98]:
#Checking column names for each 2018 quarter
q1_2018.columns

Index(['01 - Rental Details Rental ID', '01 - Rental Details Local Start Time',
       '01 - Rental Details Local End Time', '01 - Rental Details Bike ID',
       '01 - Rental Details Duration In Seconds Uncapped',
       '03 - Rental Start Station ID', '03 - Rental Start Station Name',
       '02 - Rental End Station ID', '02 - Rental End Station Name',
       'User Type', 'Member Gender',
       '05 - Member Details Member Birthday Year'],
      dtype='object')

In [99]:
#Checking column names for each 2018 quarter
q2_2018.columns

Index(['trip_id', 'start_time', 'end_time', 'bikeid', 'tripduration',
       'from_station_id', 'from_station_name', 'to_station_id',
       'to_station_name', 'usertype', 'gender', 'birthyear'],
      dtype='object')

In [100]:
#Checking column names for each 2018 quarter
q3_2018.columns

Index(['trip_id', 'start_time', 'end_time', 'bikeid', 'tripduration',
       'from_station_id', 'from_station_name', 'to_station_id',
       'to_station_name', 'usertype', 'gender', 'birthyear'],
      dtype='object')

In [101]:
#Checking column names for each 2018 quarter
q4_2018.columns

Index(['trip_id', 'start_time', 'end_time', 'bikeid', 'tripduration',
       'from_station_id', 'from_station_name', 'to_station_id',
       'to_station_name', 'usertype', 'gender', 'birthyear'],
      dtype='object')

In [102]:
#Renaming q1_2018 columns to match the format of other quarters
q1_2018 = q1_2018.rename(columns = {
    '01 - Rental Details Rental ID' : 'trip_id', 
    '01 - Rental Details Local Start Time' : 'start_time',
    '01 - Rental Details Local End Time' : 'end_time', 
    '01 - Rental Details Bike ID' : 'bikeid',
    '01 - Rental Details Duration In Seconds Uncapped' : 'tripduration',
    '03 - Rental Start Station ID' : 'from_station_id', 
    '03 - Rental Start Station Name' : 'from_station_name',
    '02 - Rental End Station ID' : 'to_station_id', 
    '02 - Rental End Station Name' : 'to_station_name',
    'User Type' : 'usertype', 
    'Member Gender' : 'gender',
    '05 - Member Details Member Birthday Year' : 'birthyear',
})

In [103]:
#Checking accuracy of columns' renaming
q1_2018.columns == q2_2018.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [104]:
#Checking accuracy of columns' types
q1_2018.info() == q2_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 387145 entries, 0 to 387144
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   trip_id            387145 non-null  int64
 1   start_time         387145 non-null  object
 2   end_time           387145 non-null  object
 3   bikeid             387145 non-null  int64
 4   tripduration       387145 non-null  object
 5   from_station_id    387145 non-null  int64
 6   from_station_name  387145 non-null  object
 7   to_station_id      387145 non-null  int64
 8   to_station_name    387145 non-null  object
 9   usertype           387145 non-null  object
 10  gender             364652 non-null  object
 11  birthyear          364823 non-null  float64
dtypes: float64(1), int64(4), object(7)
memory usage: 35.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1059681 entries, 0 to 1059680
Data columns (total 12 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   trip_id            1059681 non-null  int64
 1   start_time         1059681 non-null  object
 2   end_time           1059681 non-null  object
 3   bikeid             1059681 non-null  int64
 4   tripduration       1059681 non-null  object
 5   from_station_id    1059681 non-null  int64
 6   from_station_name  1059681 non-null  object
 7   to_station_id      1059681 non-null  int64
 8   to_station_name    1059681 non-null  object
 9   usertype           1059681 non-null  object
 10  gender             863047 non-null   object
 11  birthyear          864540 non-null   float64
dtypes: float64(1), int64(4), object(7)
memory usage: 97.0+ MB

True

In [105]:
#Joining all data from 2018
data_2018 = pd.concat([q1_2018, q2_2018, q3_2018, q4_2018], ignore_index = True)
data_2018.describe

<bound method NDFrame.describe of           trip_id           start_time             end_time  bikeid  \
0        17536702  2018-01-01 00:12:00  2018-01-01 00:17:23    3304
1        17536703  2018-01-01 00:41:35  2018-01-01 00:47:52    5367
2        17536704  2018-01-01 00:44:46  2018-01-01 01:33:10    4599
3        17536705  2018-01-01 00:53:10  2018-01-01 01:05:37    2302
4        17536706  2018-01-01 00:53:37  2018-01-01 00:56:40    3696
...           ...                  ...                  ...     ...
3603077  21742438  2018-12-31 23:45:17  2018-12-31 23:50:05    2931
3603078  21742439  2018-12-31 23:48:48  2018-12-31 23:57:22    4386
3603079  21742440  2018-12-31 23:50:09  2018-12-31 23:57:16    4927
3603080  21742441  2018-12-31 23:55:04  2018-12-31 23:58:24    1350
3603081  21742442  2018-12-31 23:59:18  2019-01-01 00:20:43    2006

        tripduration  from_station_id               from_station_name  \
0              323.0               69          Damen Ave & Pierce Ave
1              377.0              253     Winthrop Ave & Lawrence Ave
2            2,904.0               98      LaSalle St & Washington St
3              747.0              125            Rush St & Hubbard St
4              183.0              129       Blue Island Ave & 18th St
...              ...              ...                             ...
3603077        288.0               49         Dearborn St & Monroe St
3603078        514.0              624  Dearborn St & Van Buren St (*)
3603079        427.0               41            Federal St & Polk St
3603080        200.0              141          Clark St & Lincoln Ave
3603081      1,285.0              260      Kedzie Ave & Milwaukee Ave

         to_station_id                 to_station_name    usertype  gender  \
0                  159       Claremont Ave & Hirsch St  Subscriber    Male
1                  325  Clark St & Winnemac Ave (Temp)  Subscriber    Male
2                  509             Troy St & North Ave  Subscriber    Male
3                  364            Larrabee St & Oak St  Subscriber    Male
4                  205            Paulina St & 18th St  Subscriber    Male
...                ...                             ...         ...     ...
3603077            164           Franklin St & Lake St  Subscriber  Female
3603078             44          State St & Randolph St  Subscriber  Female
3603079             52          Michigan Ave & Lake St  Subscriber  Female
3603080            118         Sedgwick St & North Ave  Subscriber    Male
3603081            166    Ashland Ave & Wrightwood Ave  Subscriber    Male

         birthyear
0           1988.0
1           1984.0
2           1989.0
3           1983.0
4           1989.0
...            ...
3603077     1983.0
3603078     1990.0
3603079     1995.0
3603080     1999.0
3603081     1990.0

[3603082 rows x 12 columns]>

In [106]:
#Checking that 2019 dataset has the same column' names than 2018
q1_2019.columns == q2_2018.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [107]:
#Checking that 2019 dataset has the same column' names than 2018
q2_2019.columns == q2_2018.columns

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

In [108]:
#Checking column' names to be modified
q2_2019.columns

Index(['01 - Rental Details Rental ID', '01 - Rental Details Local Start Time',
       '01 - Rental Details Local End Time', '01 - Rental Details Bike ID',
       '01 - Rental Details Duration In Seconds Uncapped',
       '03 - Rental Start Station ID', '03 - Rental Start Station Name',
       '02 - Rental End Station ID', '02 - Rental End Station Name',
       'User Type', 'Member Gender',
       '05 - Member Details Member Birthday Year'],
      dtype='object')

In [109]:
#Checking that 2019 dataset has the same column' names than 2018
q3_2019.columns == q2_2018.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [110]:
#Checking that 2019 dataset has the same column' names than 2018
q4_2019.columns == q2_2018.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [111]:
#Renaming q2_2019 columns to match format from other quarters (& of 2018)
q2_2019 = q2_2019.rename(columns = {
    '01 - Rental Details Rental ID' : 'trip_id', 
    '01 - Rental Details Local Start Time' : 'start_time',
    '01 - Rental Details Local End Time' : 'end_time', 
    '01 - Rental Details Bike ID' : 'bikeid',
    '01 - Rental Details Duration In Seconds Uncapped' : 'tripduration',
    '03 - Rental Start Station ID' : 'from_station_id', 
    '03 - Rental Start Station Name' : 'from_station_name',
    '02 - Rental End Station ID' : 'to_station_id', 
    '02 - Rental End Station Name' : 'to_station_name',
    'User Type' : 'usertype', 
    'Member Gender' : 'gender',
    '05 - Member Details Member Birthday Year' : 'birthyear'
})

q2_2019.columns == q3_2019.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [112]:
#Checking that all q-_2019 dataframes display the same datatypes
q1_2019.info() == q2_2019.info()
q2_2019.info() == q3_2019.info()
q3_2019.info() == q4_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365069 entries, 0 to 365068
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   trip_id            365069 non-null  int64
 1   start_time         365069 non-null  object
 2   end_time           365069 non-null  object
 3   bikeid             365069 non-null  int64
 4   tripduration       365069 non-null  object
 5   from_station_id    365069 non-null  int64
 6   from_station_name  365069 non-null  object
 7   to_station_id      365069 non-null  int64
 8   to_station_name    365069 non-null  object
 9   usertype           365069 non-null  object
 10  gender             345358 non-null  object
 11  birthyear          347046 non-null  float64
dtypes: float64(1), int64(4), object(7)
memory usage: 33.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1108163 entries, 0 to 1108162
Data columns (total 12 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   trip_id            1108163 non-null  int64
 1   start_time         1108163 non-null  object
 2   end_time           1108163 non-null  object
 3   bikeid             1108163 non-null  int64
 4   tripduration       1108163 non-null  object
 5   from_station_id    1108163 non-null  int64
 6   from_station_name  1108163 non-null  object
 7   to_station_id      1108163 non-null  int64
 8   to_station_name    1108163 non-null  object
 9   usertype           1108163 non-null  object
 10  gender             922609 non-null   object
 11  birthyear          927210 non-null   float64
dtypes: float64(1), int64(4), object(7)
memory usage: 101.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1108163 entries, 0 to 1108162
Data columns (total 12 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   trip_id            1108163 non-null  int64
 1   start_time         1108163 non-null  object
 2   end_time           1108163 non-null  object
 3   bikeid             1108163 non-null  int64
 4   tripduration       1108163 non-null  object
 5   from_station_id    1108163 non-null  int64
 6   from_station_name  1108163 non-null  object
 7   to_station_id      1108163 non-null  int64
 8   to_station_name    1108163 non-null  object
 9   usertype           1108163 non-null  object
 10  gender             922609 non-null   object
 11  birthyear          927210 non-null   float64
dtypes: float64(1), int64(4), object(7)
memory usage: 101.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1640718 entries, 0 to 1640717
Data columns (total 12 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   trip_id            1640718 non-null  int64
 1   start_time         1640718 non-null  object
 2   end_time           1640718 non-null  object
 3   bikeid             1640718 non-null  int64
 4   tripduration       1640718 non-null  object
 5   from_station_id    1640718 non-null  int64
 6   from_station_name  1640718 non-null  object
 7   to_station_id      1640718 non-null  int64
 8   to_station_name    1640718 non-null  object
 9   usertype           1640718 non-null  object
 10  gender             1353368 non-null  object
 11  birthyear          1362624 non-null  float64
dtypes: float64(1), int64(4), object(7)
memory usage: 150.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1640718 entries, 0 to 1640717
Data columns (total 12 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   trip_id            1640718 non-null  int64
 1   start_time         1640718 non-null  object
 2   end_time           1640718 non-null  object
 3   bikeid             1640718 non-null  int64
 4   tripduration       1640718 non-null  object
 5   from_station_id    1640718 non-null  int64
 6   from_station_name  1640718 non-null  object
 7   to_station_id      1640718 non-null  int64
 8   to_station_name    1640718 non-null  object
 9   usertype           1640718 non-null  object
 10  gender             1353368 non-null  object
 11  birthyear          1362624 non-null  float64
dtypes: float64(1), int64(4), object(7)
memory usage: 150.2+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 704054 entries, 0 to 704053
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   trip_id            704054 non-null  int64
 1   start_time         704054 non-null  object
 2   end_time           704054 non-null  object
 3   bikeid             704054 non-null  int64
 4   tripduration       704054 non-null  object
 5   from_station_id    704054 non-null  int64
 6   from_station_name  704054 non-null  object
 7   to_station_id      704054 non-null  int64
 8   to_station_name    704054 non-null  object
 9   usertype           704054 non-null  object
 10  gender             637463 non-null  object
 11  birthyear          642373 non-null  float64
dtypes: float64(1), int64(4), object(7)
memory usage: 64.5+ MB

True

In [113]:
#Joining all data from 2019
data_2019 = pd.concat([q1_2019, q2_2019, q3_2019, q4_2019], ignore_index = True)
data_2019.describe

<bound method NDFrame.describe of           trip_id           start_time             end_time  bikeid  \
0        21742443  2019-01-01 00:04:37  2019-01-01 00:11:07    2167
1        21742444  2019-01-01 00:08:13  2019-01-01 00:15:34    4386
2        21742445  2019-01-01 00:13:23  2019-01-01 00:27:12    1524
3        21742446  2019-01-01 00:13:45  2019-01-01 00:43:28     252
4        21742447  2019-01-01 00:14:52  2019-01-01 00:20:56    1170
...           ...                  ...                  ...     ...
3817999  25962900  2019-12-31 23:56:13  2020-01-01 00:15:45    2196
3818000  25962901  2019-12-31 23:56:34  2020-01-01 00:22:08    4877
3818001  25962902  2019-12-31 23:57:05  2020-01-01 00:05:46     863
3818002  25962903  2019-12-31 23:57:11  2020-01-01 00:05:45    2637
3818003  25962904  2019-12-31 23:57:17  2019-12-31 23:59:18    5930

        tripduration  from_station_id                    from_station_name  \
0              390.0              199               Wabash Ave & Grand Ave
1              441.0               44               State St & Randolph St
2              829.0               15                 Racine Ave & 18th St
3            1,783.0              123       California Ave & Milwaukee Ave
4              364.0              173  Mies van der Rohe Way & Chicago Ave
...              ...              ...                                  ...
3817999      1,172.0              112               Green St & Randolph St
3818000      1,533.0               90                      Millennium Park
3818001        520.0              623                Michigan Ave & 8th St
3818002        514.0              623                Michigan Ave & 8th St
3818003        120.0              256               Broadway & Sheridan Rd

         to_station_id                 to_station_name    usertype  gender  \
0                   84       Milwaukee Ave & Grand Ave  Subscriber    Male
1                  624  Dearborn St & Van Buren St (*)  Subscriber  Female
2                  644   Western Ave & Fillmore St (*)  Subscriber  Female
3                  176               Clark St & Elm St  Subscriber    Male
4                   35         Streeter Dr & Grand Ave  Subscriber    Male
...                ...                             ...         ...     ...
3817999            225        Halsted St & Dickens Ave  Subscriber    Male
3818000             90                 Millennium Park  Subscriber    Male
3818001             52          Michigan Ave & Lake St  Subscriber    Male
3818002             52          Michigan Ave & Lake St  Subscriber  Female
3818003            240    Sheridan Rd & Irving Park Rd  Subscriber    Male

         birthyear
0           1989.0
1           1990.0
2           1994.0
3           1993.0
4           1994.0
...            ...
3817999     1981.0
3818000     1992.0
3818001     1967.0
3818002     1970.0
3818003     1982.0

[3818004 rows x 12 columns]>

In [114]:
#Joining 2018 & 2019 datasets
all_trips = pd.concat([data_2018, data_2019], ignore_index = True)
all_trips.describe

<bound method NDFrame.describe of           trip_id           start_time             end_time  bikeid  \
0        17536702  2018-01-01 00:12:00  2018-01-01 00:17:23    3304
1        17536703  2018-01-01 00:41:35  2018-01-01 00:47:52    5367
2        17536704  2018-01-01 00:44:46  2018-01-01 01:33:10    4599
3        17536705  2018-01-01 00:53:10  2018-01-01 01:05:37    2302
4        17536706  2018-01-01 00:53:37  2018-01-01 00:56:40    3696
...           ...                  ...                  ...     ...
7421081  25962900  2019-12-31 23:56:13  2020-01-01 00:15:45    2196
7421082  25962901  2019-12-31 23:56:34  2020-01-01 00:22:08    4877
7421083  25962902  2019-12-31 23:57:05  2020-01-01 00:05:46     863
7421084  25962903  2019-12-31 23:57:11  2020-01-01 00:05:45    2637
7421085  25962904  2019-12-31 23:57:17  2019-12-31 23:59:18    5930

        tripduration  from_station_id            from_station_name  \
0              323.0               69       Damen Ave & Pierce Ave
1              377.0              253  Winthrop Ave & Lawrence Ave
2            2,904.0               98   LaSalle St & Washington St
3              747.0              125         Rush St & Hubbard St
4              183.0              129    Blue Island Ave & 18th St
...              ...              ...                          ...
7421081      1,172.0              112       Green St & Randolph St
7421082      1,533.0               90              Millennium Park
7421083        520.0              623        Michigan Ave & 8th St
7421084        514.0              623        Michigan Ave & 8th St
7421085        120.0              256       Broadway & Sheridan Rd

         to_station_id                 to_station_name    usertype  gender  \
0                  159       Claremont Ave & Hirsch St  Subscriber    Male
1                  325  Clark St & Winnemac Ave (Temp)  Subscriber    Male
2                  509             Troy St & North Ave  Subscriber    Male
3                  364            Larrabee St & Oak St  Subscriber    Male
4                  205            Paulina St & 18th St  Subscriber    Male
...                ...                             ...         ...     ...
7421081            225        Halsted St & Dickens Ave  Subscriber    Male
7421082             90                 Millennium Park  Subscriber    Male
7421083             52          Michigan Ave & Lake St  Subscriber    Male
7421084             52          Michigan Ave & Lake St  Subscriber  Female
7421085            240    Sheridan Rd & Irving Park Rd  Subscriber    Male

         birthyear
0           1988.0
1           1984.0
2           1989.0
3           1983.0
4           1989.0
...            ...
7421081     1981.0
7421082     1992.0
7421083     1967.0
7421084     1970.0
7421085     1982.0

[7421086 rows x 12 columns]>

In [115]:
#Data cleaning
#Checking for inconsistencies in 'usertype' column
all_trips['usertype'].value_counts()

usertype
Subscriber    5863293
Customer      1557793
Name: count, dtype: int64

In [116]:
#Data cleaning
#Checking if there are any rows corresponding to some kind of maintenance in 'from_station_name' column
all_trips['from_station_name'].value_counts()

from_station_name
Streeter Dr & Grand Ave         134927
Canal St & Adams St             117043
Clinton St & Madison St         101600
Clinton St & Washington Blvd     96822
Lake Shore Dr & Monroe St        85978
                                 ...
Oak Park Ave & Harrison St           3
Humphrey Ave & Ontario St            2
LBS - BBB La Magie                   1
Special Events                       1
TS ~ DIVVY PARTS TESTING             1
Name: count, Length: 664, dtype: int64

In [117]:
#Data formatting
#Converting 'start_time' & 'end_time' columns into datetime values
all_trips['start_time'] = pd.to_datetime(all_trips['start_time'])
all_trips['end_time'] = pd.to_datetime(all_trips['end_time'])
all_trips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7421086 entries, 0 to 7421085
Data columns (total 12 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   start_time         datetime64[ns]
 2   end_time           datetime64[ns]
 3   bikeid             int64
 4   tripduration       object
 5   from_station_id    int64
 6   from_station_name  object
 7   to_station_id      int64
 8   to_station_name    object
 9   usertype           object
 10  gender             object
 11  birthyear          float64
dtypes: datetime64[ns](2), float64(1), int64(4), object(5)
memory usage: 679.4+ MB

In [118]:
#Data formatting
#Extracting date, day, month from 'start_time' column & droping 'tripduration' column as it's a string type
all_trips['date'] = all_trips['start_time'].dt.date
all_trips['day'] = all_trips['start_time'].dt.day
all_trips['month'] = all_trips['start_time'].dt.month
all_trips = all_trips.drop(columns = ['tripduration'])
all_trips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7421086 entries, 0 to 7421085
Data columns (total 14 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   start_time         datetime64[ns]
 2   end_time           datetime64[ns]
 3   bikeid             int64
 4   from_station_id    int64
 5   from_station_name  object
 6   to_station_id      int64
 7   to_station_name    object
 8   usertype           object
 9   gender             object
 10  birthyear          float64
 11  date               object
 12  day                int32
 13  month              int32
dtypes: datetime64[ns](2), float64(1), int32(2), int64(4), object(5)
memory usage: 736.0+ MB

In [119]:
#Data formatting
#Creating a tripduration_min column
all_trips['tripduration'] = (all_trips['end_time'] - all_trips['start_time']).dt.total_seconds()
all_trips['tripduration_min'] = all_trips['tripduration'] / 60
all_trips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7421086 entries, 0 to 7421085
Data columns (total 16 columns):
 #   Column             Dtype
---  ------             -----
 0   trip_id            int64
 1   start_time         datetime64[ns]
 2   end_time           datetime64[ns]
 3   bikeid             int64
 4   from_station_id    int64
 5   from_station_name  object
 6   to_station_id      int64
 7   to_station_name    object
 8   usertype           object
 9   gender             object
 10  birthyear          float64
 11  date               object
 12  day                int32
 13  month              int32
 14  tripduration       float64
 15  tripduration_min   float64
dtypes: datetime64[ns](2), float64(3), int32(2), int64(4), object(5)
memory usage: 849.3+ MB

In [120]:
#Data cleaning
#Checking outlier values for tripduration_min
all_trips['tripduration_min'].describe()

count    7.421086e+06
mean     2.387225e+01
std      5.491889e+02
min     -5.636667e+01
25%      6.716667e+00
50%      1.151667e+01
75%      2.078333e+01
max      2.390007e+05
Name: tripduration_min, dtype: float64

In [121]:
#Data cleaning
#Removing trip durations less than 1 min & more than 24h, 
#as well as rows from from_station_name indicating some kind of maintenance
all_trips_v2 = all_trips[
    (all_trips['from_station_name'] != "LBS - BBB La Magie") & 
    (all_trips['from_station_name'] != "Special Events") &
    (all_trips['from_station_name'] != "TS ~ DIVVY PARTS TESTING") &
    (all_trips['from_station_name'] != "BBB ~ Divvy Parts Testing") &
    (all_trips['tripduration_min'] >= 1) & 
    (all_trips['tripduration_min'] <= 1440)].copy()

all_trips_v2['tripduration_min'].describe()

count    7.417700e+06
mean     1.864752e+01
std      3.413448e+01
min      1.016667e+00
25%      6.716667e+00
50%      1.151667e+01
75%      2.076667e+01
max      1.439750e+03
Name: tripduration_min, dtype: float64

In [122]:
#Data cleaning
#Checking cleaning in 'from_station_name' column
all_trips_v2['from_station_name'].value_counts()

from_station_name
Streeter Dr & Grand Ave         134854
Canal St & Adams St             117020
Clinton St & Madison St         101582
Clinton St & Washington Blvd     96810
Lake Shore Dr & Monroe St        85927
                                 ...
East Ave & Garfield St               9
Lombard Ave & Madison St             8
Elizabeth St & 59th St               8
Oak Park Ave & Harrison St           3
Humphrey Ave & Ontario St            2
Name: count, Length: 660, dtype: int64

In [123]:
#Data formatting
#Transforming 'date' column to datetime type & then extracting day_of_week
all_trips_v2['date'] = pd.to_datetime(all_trips_v2['date'])
all_trips_v2['day_of_week'] = all_trips_v2['date'].dt.day_name()
all_trips_v2.head()

,trip_id,start_time,end_time,bikeid,from_station_id,from_station_name,to_station_id,to_station_name,usertype,gender,birthyear,date,day,month,tripduration,tripduration_min,day_of_week
0,17536702,2018-01-01 00:12:00,2018-01-01 00:17:23,3304,69,Damen Ave & Pierce Ave,159,Claremont Ave & Hirsch St,Subscriber,Male,1988.0,2018-01-01,1,1,323.0,5.383333,Monday
1,17536703,2018-01-01 00:41:35,2018-01-01 00:47:52,5367,253,Winthrop Ave & Lawrence Ave,325,Clark St & Winnemac Ave (Temp),Subscriber,Male,1984.0,2018-01-01,1,1,377.0,6.283333,Monday
2,17536704,2018-01-01 00:44:46,2018-01-01 01:33:10,4599,98,LaSalle St & Washington St,509,Troy St & North Ave,Subscriber,Male,1989.0,2018-01-01,1,1,2904.0,48.400000,Monday
3,17536705,2018-01-01 00:53:10,2018-01-01 01:05:37,2302,125,Rush St & Hubbard St,364,Larrabee St & Oak St,Subscriber,Male,1983.0,2018-01-01,1,1,747.0,12.450000,Monday
4,17536706,2018-01-01 00:53:37,2018-01-01 00:56:40,3696,129,Blue Island Ave & 18th St,205,Paulina St & 18th St,Subscriber,Male,1989.0,2018-01-01,1,1,183.0,3.050000,Monday

In [124]:
#Data cleaning
#Checking 'birthyear' inaccuracies 
all_trips_v2['birthyear'].describe()

count    6.325528e+06
mean     1.983408e+03
std      1.092036e+01
min      1.759000e+03
25%      1.978000e+03
50%      1.987000e+03
75%      1.991000e+03
max      2.014000e+03
Name: birthyear, dtype: float64

In [125]:
#Data cleaning
#Checking how many rows are probably inaccurate for 'birthyear' column 
trip_year = 2019
age = trip_year - all_trips_v2['birthyear']

suspect_rows = all_trips_v2[(age > 90) | (age < 10)]
suspect_rows.shape[0]

2340

In [126]:
#Data cleaning
#Removing 'birthyear' probably inaccurate rows
all_trips_v3 = all_trips_v2[
    (age < 90) & (age > 10)].copy()
all_trips_v3['birthyear'].describe()

count    6.323180e+06
mean     1.983435e+03
std      1.082934e+01
min      1.930000e+03
25%      1.978000e+03
50%      1.987000e+03
75%      1.991000e+03
max      2.005000e+03
Name: birthyear, dtype: float64

In [142]:
#Data analysis
#User type distribution
all_trips_v3['usertype'].value_counts()

usertype
Subscriber    5850351
Customer       472829
Name: count, dtype: int64

In [127]:
#Data analysis
#Gender distribution
all_trips_v3['gender'].value_counts()

gender
Male      4679403
Female    1616145
Name: count, dtype: int64

In [128]:
#Data analysis
#Usertype distribution
all_trips_v3['usertype'].value_counts()

usertype
Subscriber    5850351
Customer       472829
Name: count, dtype: int64

In [129]:
#Data analysis
#Age distribution
all_trips_v3['age'] = trip_year - all_trips_v3['birthyear']

print("\nAge statistics grouped by gender & usertype:\n", 
    all_trips_v3.groupby(['gender', 'usertype'])['age'].agg(['count','mean', 'median', 'min', 'max']))

Age statistics grouped by gender & usertype:
                      count       mean  median   min   max
gender usertype
Female Customer     180131  30.533367    28.0  16.0  88.0
       Subscriber  1436014  34.575586    31.0  14.0  89.0
Male   Customer     287084  31.929609    29.0  16.0  85.0
       Subscriber  4392319  36.329059    33.0  16.0  89.0

In [130]:
#Data analysis
#Age groups (under or over 30yo)
print("\nNumber of users older than 30yo:\n", 
    all_trips_v3[(all_trips_v3['age'] > 30)].groupby(['gender', 'usertype'])['age'].agg(['count']))

Number of users older than 30yo:
                      count
gender usertype
Female Customer      63570
       Subscriber   757723
Male   Customer     124855
       Subscriber  2738560

In [131]:
#Data analysis
#Age groups (under or over 30yo)
print("\nNumber of users younger than 30yo:\n", 
all_trips_v3[(all_trips_v3['age'] <= 30)].groupby(['gender', 'usertype'])['age'].agg(['count']))

Number of users younger than 30yo:
                      count
gender usertype
Female Customer     116561
       Subscriber   678291
Male   Customer     162229
       Subscriber  1653759

In [132]:
#Data analysis
#Age groups (under or over 30yo) & trip duration
print("\nTrip duration statistics of users older than 30yo:\n", 
    all_trips_v3[(all_trips_v3['age'] > 30)].groupby(['gender', 'usertype'])['tripduration_min'].agg(['mean', 'median']))

Trip duration statistics of users older than 30yo:
                         mean     median
gender usertype
Female Customer    44.335573  29.300000
       Subscriber  14.359703  11.200000
Male   Customer    38.272076  24.166667
       Subscriber  12.279600   9.333333

In [133]:
#Data analysis
#Age groups (under or over 30yo) & trip duration
print("\nTrip duration statistics of users younger than 30yo:\n", 
    all_trips_v3[(all_trips_v3['age'] < 30)].groupby(['gender', 'usertype'])['tripduration_min'].agg(['mean', 'median']))

Trip duration statistics of users younger than 30yo:
                         mean     median
gender usertype
Female Customer    36.995184  25.383333
       Subscriber  14.135446  10.916667
Male   Customer    31.250074  19.766667
       Subscriber  12.330893   9.083333

In [134]:
#Data analysis
#Trip duration regarding user type
print("\nTrip duration statistics grouped by usertype:\n", 
      all_trips_v3.groupby('usertype')['tripduration_min'].agg(['mean', 'median']))

Trip duration statistics grouped by usertype:
                  mean     median
usertype
Customer    36.559859  23.600000
Subscriber  12.781780   9.666667

In [135]:
#Data analysis
#Trip duration statistics regarding user type & day of the week
weekly_stats = all_trips_v3.groupby(['usertype', 'day_of_week'])['tripduration_min'].agg(['count', 'mean', 'median'])
weekly_stats

                         count       mean     median
usertype   day_of_week
Customer   Friday        63025  35.207787  22.566667
           Monday        56155  36.156487  23.083333
           Saturday     108632  39.817116  26.766667
           Sunday        90058  39.343810  25.650000
           Thursday      55099  33.468659  21.066667
           Tuesday       48959  33.554154  20.650000
           Wednesday     50901  33.038996  20.866667
Subscriber Friday       897984  12.370046   9.383333
           Monday       904976  12.535907   9.550000
           Saturday     569488  14.255286  10.533333
           Sunday       515479  14.234857  10.500000
           Thursday     976252  12.429172   9.516667
           Tuesday      989089  12.414460   9.516667
           Wednesday    997083  12.492548   9.566667

In [136]:
#Data analysis
#Trip duration statistics regarding user type & month of the year
monthly_stats = all_trips_v3.groupby(['usertype', 'month'])['tripduration_min'].agg(['count', 'mean', 'median'])
monthly_stats

                   count       mean     median
usertype   month
Customer   1        1216  27.461335  16.583333
           2         782  24.588043  13.966667
           3        4179  33.282073  21.816667
           4       13407  38.324326  25.966667
           5       31191  39.850648  26.650000
           6       60363  37.163740  24.666667
           7      106125  38.394192  25.500000
           8      111635  36.835040  23.816667
           9       81455  35.362822  22.633333
           10      43283  32.481735  19.583333
           11      11030  31.447396  15.200000
           12       8163  33.667837  16.916667
Subscriber 1      204397  10.665105   8.133333
           2      192640  10.933896   8.183333
           3      308051  10.923336   8.350000
           4      395015  11.931452   9.066667
           5      596494  13.194813  10.066667
           6      694325  13.815692  10.583333
           7      774016  14.102521  10.866667
           8      803265  13.704522  10.516667
           9      706630  13.169688  10.033333
           10     600482  12.174454   9.150000
           11     315428  11.188138   8.433333
           12     259608  11.096715   8.333333

In [137]:
#Data analysis
#Calculating percentage of roundtrips depending on usertype
all_trips_v3['round_trip'] = (
    all_trips_v3['from_station_name']
    == all_trips_v3['to_station_name']
)

all_trips_v3.groupby('usertype')['round_trip'].mean() * 100

usertype
Customer      8.279737
Subscriber    1.610485
Name: round_trip, dtype: float64

In [138]:
#Data analysis
#Calculating average tripduration on roundtrips depending on usertype
print("\nAverage trip duration on roundtrips by user type:\n", 
    all_trips_v3.groupby(['usertype', 'round_trip'])['tripduration_min'].mean())

Average trip duration on roundtrips by user type:
 usertype    round_trip
Customer    False         34.485436
            True          59.539652
Subscriber  False         12.603607
            True          23.666928
Name: tripduration_min, dtype: float64

In [139]:
#Data analysis
#Calculating top 5 pair stations depending on usertype
top_pairs = (all_trips_v3.groupby([
        'usertype',
        'from_station_name',
        'to_station_name'
    ])
    .size()
    .reset_index(name='number_of_rides')
    .sort_values('number_of_rides', ascending=False)
)

topstations_subs = top_pairs[top_pairs['usertype'] == 'Subscriber'].head(5)
topstations_subs

,usertype,from_station_name,to_station_name,number_of_rides
89287,Subscriber,Canal St & Adams St,Michigan Ave & Washington St,7447
159477,Subscriber,Michigan Ave & Washington St,Canal St & Adams St,6573
159528,Subscriber,Michigan Ave & Washington St,Clinton St & Washington Blvd,6090
106408,Subscriber,Columbus Dr & Randolph St,Clinton St & Washington Blvd,5092
196460,Subscriber,Wacker Dr & Washington St,Michigan Ave & Washington St,5055

In [140]:
#Data analysis
#Calculating top 5 pair stations depending on usertype
topstations_cust = top_pairs[top_pairs['usertype'] == 'Customer'].head(5)
topstations_cust

,usertype,from_station_name,to_station_name,number_of_rides
62764,Customer,Streeter Dr & Grand Ave,Streeter Dr & Grand Ave,2626
36051,Customer,Lake Shore Dr & Monroe St,Streeter Dr & Grand Ave,2558
35927,Customer,Lake Shore Dr & Monroe St,Lake Shore Dr & Monroe St,1775
44959,Customer,Michigan Ave & Oak St,Michigan Ave & Oak St,1652
62663,Customer,Streeter Dr & Grand Ave,Millennium Park,1490

In [141]:
#Saving all stats to create visualizations
weekly_stats.to_csv('bikeshare2018to2019_weeklystats.csv')
monthly_stats.to_csv('bikeshare2018to2019_monthlystats.csv')
topstations_subs.to_csv('bikeshare2018to2019_topstations_subs.csv', index=False)
topstations_cust.to_csv('bikeshare2018to2019_topstations_cust.csv', index=False)